import Head from 'next/head';
import { styled } from '@src/styles/stitches.config';

const Text = styled('p', {
    fontFamily: '$system',
    color: '$hiContrast',

    variants: {
        size: {
            1: {
                fontSize: '$1',
            },
            2: {
                fontSize: '$2',
            },
            3: {
                fontSize: '$3',
            },
        },
    },
});

export default function Home() {
    return (
        <div>
            <Head>
                <title>iCritic</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main>
                <Text size="3">iCritic</Text>
            </main>
        </div>
    );
}
