CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(1000)
);
INSERT INTO countries (Name) VALUES ('Afghanistan');
INSERT INTO countries (Name) VALUES ('Albania');
INSERT INTO countries (Name) VALUES ('Algeria');
INSERT INTO countries (Name) VALUES ('American Samoa');
INSERT INTO countries (Name) VALUES ('Andorra');
INSERT INTO countries (Name) VALUES ('Angola');
INSERT INTO countries (Name) VALUES ('Anguilla');
INSERT INTO countries (Name) VALUES ('Antarctica');
INSERT INTO countries (Name) VALUES ('Antigua and Barbuda');
INSERT INTO countries (Name) VALUES ('Argentina');
INSERT INTO countries (Name) VALUES ('Armenia');
INSERT INTO countries (Name) VALUES ('Aruba');
INSERT INTO countries (Name) VALUES ('Australia');
INSERT INTO countries (Name) VALUES ('Austria');
INSERT INTO countries (Name) VALUES ('Azerbaijan');
INSERT INTO countries (Name) VALUES ('Bahamas');
INSERT INTO countries (Name) VALUES ('Bahrain');
INSERT INTO countries (Name) VALUES ('Bangladesh');
INSERT INTO countries (Name) VALUES ('Barbados');
INSERT INTO countries (Name) VALUES ('Belarus');
INSERT INTO countries (Name) VALUES ('Belgium');
INSERT INTO countries (Name) VALUES ('Belize');
INSERT INTO countries (Name) VALUES ('Benin');
INSERT INTO countries (Name) VALUES ('Bermuda');
INSERT INTO countries (Name) VALUES ('Bhutan');
INSERT INTO countries (Name) VALUES ('Bosnia and Herzegovina');
INSERT INTO countries (Name) VALUES ('Botswana');
INSERT INTO countries (Name) VALUES ('Bouvet Island');
INSERT INTO countries (Name) VALUES ('Brazil');
INSERT INTO countries (Name) VALUES ('British Indian Ocean Territory');
INSERT INTO countries (Name) VALUES ('Brunei Darussalam');
INSERT INTO countries (Name) VALUES ('Bulgaria');
INSERT INTO countries (Name) VALUES ('Burkina Faso');
INSERT INTO countries (Name) VALUES ('Burundi');
INSERT INTO countries (Name) VALUES ('Cambodia');
INSERT INTO countries (Name) VALUES ('Cameroon');
INSERT INTO countries (Name) VALUES ('Canada');
INSERT INTO countries (Name) VALUES ('Cape Verde');
INSERT INTO countries (Name) VALUES ('Cayman Islands');
INSERT INTO countries (Name) VALUES ('Central African Republic');
INSERT INTO countries (Name) VALUES ('Chad');
INSERT INTO countries (Name) VALUES ('Chile');
INSERT INTO countries (Name) VALUES ('China');
INSERT INTO countries (Name) VALUES ('Christmas Island');
INSERT INTO countries (Name) VALUES ('Cocos (Keeling) Islands');
INSERT INTO countries (Name) VALUES ('Colombia');
INSERT INTO countries (Name) VALUES ('Comoros');
INSERT INTO countries (Name) VALUES ('Congo');
INSERT INTO countries (Name) VALUES ('Cook Islands');
INSERT INTO countries (Name) VALUES ('Costa Rica');
INSERT INTO countries (Name) VALUES ('Croatia');
INSERT INTO countries (Name) VALUES ('Cuba');
INSERT INTO countries (Name) VALUES ('Cyprus');
INSERT INTO countries (Name) VALUES ('Czech Republic');
INSERT INTO countries (Name) VALUES ('Denmark');
INSERT INTO countries (Name) VALUES ('Djibouti');
INSERT INTO countries (Name) VALUES ('Dominica');
INSERT INTO countries (Name) VALUES ('Dominican Republic');
INSERT INTO countries (Name) VALUES ('Ecuador');
INSERT INTO countries (Name) VALUES ('Egypt');
INSERT INTO countries (Name) VALUES ('El Salvador');
INSERT INTO countries (Name) VALUES ('Equatorial Guinea');
INSERT INTO countries (Name) VALUES ('Eritrea');
INSERT INTO countries (Name) VALUES ('Estonia');
INSERT INTO countries (Name) VALUES ('Ethiopia');
INSERT INTO countries (Name) VALUES ('Falkland Islands (Malvinas)');
INSERT INTO countries (Name) VALUES ('Faroe Islands');
INSERT INTO countries (Name) VALUES ('Fiji');
INSERT INTO countries (Name) VALUES ('Finland');
INSERT INTO countries (Name) VALUES ('France');
INSERT INTO countries (Name) VALUES ('French Guiana');
INSERT INTO countries (Name) VALUES ('French Polynesia');
INSERT INTO countries (Name) VALUES ('French Southern Territories');
INSERT INTO countries (Name) VALUES ('Gabon');
INSERT INTO countries (Name) VALUES ('Gambia');
INSERT INTO countries (Name) VALUES ('Georgia');
INSERT INTO countries (Name) VALUES ('Germany');
INSERT INTO countries (Name) VALUES ('Ghana');
INSERT INTO countries (Name) VALUES ('Gibraltar');
INSERT INTO countries (Name) VALUES ('Greece');
INSERT INTO countries (Name) VALUES ('Greenland');
INSERT INTO countries (Name) VALUES ('Grenada');
INSERT INTO countries (Name) VALUES ('Guadeloupe');
INSERT INTO countries (Name) VALUES ('Guam');
INSERT INTO countries (Name) VALUES ('Guatemala');
INSERT INTO countries (Name) VALUES ('Guernsey');
INSERT INTO countries (Name) VALUES ('Guinea');
INSERT INTO countries (Name) VALUES ('Guinea-Bissau');
INSERT INTO countries (Name) VALUES ('Guyana');
INSERT INTO countries (Name) VALUES ('Haiti');
INSERT INTO countries (Name) VALUES ('Heard Island and McDonald Islands');
INSERT INTO countries (Name) VALUES ('Holy See (Vatican City State)');
INSERT INTO countries (Name) VALUES ('Honduras');
INSERT INTO countries (Name) VALUES ('Hong Kong');
INSERT INTO countries (Name) VALUES ('Hungary');
INSERT INTO countries (Name) VALUES ('Iceland');
INSERT INTO countries (Name) VALUES ('India');
INSERT INTO countries (Name) VALUES ('Indonesia');
INSERT INTO countries (Name) VALUES ('Iraq');
INSERT INTO countries (Name) VALUES ('Ireland');
INSERT INTO countries (Name) VALUES ('Isle of Man');
INSERT INTO countries (Name) VALUES ('Israel');
INSERT INTO countries (Name) VALUES ('Italy');
INSERT INTO countries (Name) VALUES ('Jamaica');
INSERT INTO countries (Name) VALUES ('Japan');
INSERT INTO countries (Name) VALUES ('Jersey');
INSERT INTO countries (Name) VALUES ('Jordan');
INSERT INTO countries (Name) VALUES ('Kazakhstan');
INSERT INTO countries (Name) VALUES ('Kenya');
INSERT INTO countries (Name) VALUES ('Kiribati');
INSERT INTO countries (Name) VALUES ('Kuwait');
INSERT INTO countries (Name) VALUES ('Kyrgyzstan');
INSERT INTO countries (Name) VALUES ('Lao Peoples Democratic Republic');
INSERT INTO countries (Name) VALUES ('Latvia');
INSERT INTO countries (Name) VALUES ('Lebanon');
INSERT INTO countries (Name) VALUES ('Lesotho');
INSERT INTO countries (Name) VALUES ('Liberia');
INSERT INTO countries (Name) VALUES ('Libya');
INSERT INTO countries (Name) VALUES ('Liechtenstein');
INSERT INTO countries (Name) VALUES ('Lithuania');
INSERT INTO countries (Name) VALUES ('Luxembourg');
INSERT INTO countries (Name) VALUES ('Macao');
INSERT INTO countries (Name) VALUES ('Madagascar');
INSERT INTO countries (Name) VALUES ('Malawi');
INSERT INTO countries (Name) VALUES ('Malaysia');
INSERT INTO countries (Name) VALUES ('Maldives');
INSERT INTO countries (Name) VALUES ('Mali');
INSERT INTO countries (Name) VALUES ('Malta');
INSERT INTO countries (Name) VALUES ('Marshall Islands');
INSERT INTO countries (Name) VALUES ('Martinique');
INSERT INTO countries (Name) VALUES ('Mauritania');
INSERT INTO countries (Name) VALUES ('Mauritius');
INSERT INTO countries (Name) VALUES ('Mayotte');
INSERT INTO countries (Name) VALUES ('Mexico');
INSERT INTO countries (Name) VALUES ('Monaco');
INSERT INTO countries (Name) VALUES ('Mongolia');
INSERT INTO countries (Name) VALUES ('Montenegro');
INSERT INTO countries (Name) VALUES ('Montserrat');
INSERT INTO countries (Name) VALUES ('Morocco');
INSERT INTO countries (Name) VALUES ('Mozambique');
INSERT INTO countries (Name) VALUES ('Myanmar');
INSERT INTO countries (Name) VALUES ('Namibia');
INSERT INTO countries (Name) VALUES ('Nauru');
INSERT INTO countries (Name) VALUES ('Nepal');
INSERT INTO countries (Name) VALUES ('Netherlands');
INSERT INTO countries (Name) VALUES ('New Caledonia');
INSERT INTO countries (Name) VALUES ('New Zealand');
INSERT INTO countries (Name) VALUES ('Nicaragua');
INSERT INTO countries (Name) VALUES ('Niger');
INSERT INTO countries (Name) VALUES ('Nigeria');
INSERT INTO countries (Name) VALUES ('Niue');
INSERT INTO countries (Name) VALUES ('Norfolk Island');
INSERT INTO countries (Name) VALUES ('Northern Mariana Islands');
INSERT INTO countries (Name) VALUES ('Norway');
INSERT INTO countries (Name) VALUES ('Oman');
INSERT INTO countries (Name) VALUES ('Pakistan');
INSERT INTO countries (Name) VALUES ('Palau');
INSERT INTO countries (Name) VALUES ('Panama');
INSERT INTO countries (Name) VALUES ('Papua New Guinea');
INSERT INTO countries (Name) VALUES ('Paraguay');
INSERT INTO countries (Name) VALUES ('Peru');
INSERT INTO countries (Name) VALUES ('Philippines');
INSERT INTO countries (Name) VALUES ('Pitcairn');
INSERT INTO countries (Name) VALUES ('Poland');
INSERT INTO countries (Name) VALUES ('Portugal');
INSERT INTO countries (Name) VALUES ('Puerto Rico');
INSERT INTO countries (Name) VALUES ('Qatar');
INSERT INTO countries (Name) VALUES ('Romania');
INSERT INTO countries (Name) VALUES ('Russian Federation');
INSERT INTO countries (Name) VALUES ('Rwanda');
INSERT INTO countries (Name) VALUES ('Saint Kitts and Nevis');
INSERT INTO countries (Name) VALUES ('Saint Lucia');
INSERT INTO countries (Name) VALUES ('Saint Martin (French part)');
INSERT INTO countries (Name) VALUES ('Saint Pierre and Miquelon');
INSERT INTO countries (Name) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO countries (Name) VALUES ('Samoa');
INSERT INTO countries (Name) VALUES ('San Marino');
INSERT INTO countries (Name) VALUES ('Sao Tome and Principe');
INSERT INTO countries (Name) VALUES ('Saudi Arabia');
INSERT INTO countries (Name) VALUES ('Senegal');
INSERT INTO countries (Name) VALUES ('Serbia');
INSERT INTO countries (Name) VALUES ('Seychelles');
INSERT INTO countries (Name) VALUES ('Sierra Leone');
INSERT INTO countries (Name) VALUES ('Singapore');
INSERT INTO countries (Name) VALUES ('Sint Maarten (Dutch part)');
INSERT INTO countries (Name) VALUES ('Slovakia');
INSERT INTO countries (Name) VALUES ('Slovenia');
INSERT INTO countries (Name) VALUES ('Solomon Islands');
INSERT INTO countries (Name) VALUES ('Somalia');
INSERT INTO countries (Name) VALUES ('South Africa');
INSERT INTO countries (Name) VALUES ('South Georgia and the South Sandwich Islands');
INSERT INTO countries (Name) VALUES ('South Sudan');
INSERT INTO countries (Name) VALUES ('Spain');
INSERT INTO countries (Name) VALUES ('Sri Lanka');
INSERT INTO countries (Name) VALUES ('Sudan');
INSERT INTO countries (Name) VALUES ('Suriname');
INSERT INTO countries (Name) VALUES ('Svalbard and Jan Mayen');
INSERT INTO countries (Name) VALUES ('Swaziland');
INSERT INTO countries (Name) VALUES ('Sweden');
INSERT INTO countries (Name) VALUES ('Switzerland');
INSERT INTO countries (Name) VALUES ('Syrian Arab Republic');
INSERT INTO countries (Name) VALUES ('Tajikistan');
INSERT INTO countries (Name) VALUES ('Thailand');
INSERT INTO countries (Name) VALUES ('Timor-Leste');
INSERT INTO countries (Name) VALUES ('Togo');
INSERT INTO countries (Name) VALUES ('Tokelau');
INSERT INTO countries (Name) VALUES ('Tonga');
INSERT INTO countries (Name) VALUES ('Trinidad and Tobago');
INSERT INTO countries (Name) VALUES ('Tunisia');
INSERT INTO countries (Name) VALUES ('Turkey');
INSERT INTO countries (Name) VALUES ('Turkmenistan');
INSERT INTO countries (Name) VALUES ('Turks and Caicos Islands');
INSERT INTO countries (Name) VALUES ('Tuvalu');
INSERT INTO countries (Name) VALUES ('Uganda');
INSERT INTO countries (Name) VALUES ('Ukraine');
INSERT INTO countries (Name) VALUES ('United Arab Emirates');
INSERT INTO countries (Name) VALUES ('United Kingdom');
INSERT INTO countries (Name) VALUES ('United States');
INSERT INTO countries (Name) VALUES ('United States Minor Outlying Islands');
INSERT INTO countries (Name) VALUES ('Uruguay');
INSERT INTO countries (Name) VALUES ('Uzbekistan');
INSERT INTO countries (Name) VALUES ('Vanuatu');
INSERT INTO countries (Name) VALUES ('Viet Nam');
INSERT INTO countries (Name) VALUES ('Wallis and Futuna');
INSERT INTO countries (Name) VALUES ('Western Sahara');
INSERT INTO countries (Name) VALUES ('Yemen');
INSERT INTO countries (Name) VALUES ('Zambia');
INSERT INTO countries (Name) VALUES ('Zimbabwe');
